[package]
name = "web-axum-askama"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version =  "1.47.1", features = ["full"] }
axum = { version = "0.7.5", features = ["macros"] }
askama ={version = "0.12.1"}
tower-http = {version = "0.5.2", features = ["fs"]}